package main

// 0 ~ 999
const (
	ERROR_CODE_NONE = 0

	ERROR_CODE_PACKET_DECODING_FAIL       = 51

	ERROR_CODE_LOGIN_USER_INVALID_ID    = 112
	ERROR_CODE_LOGIN_USER_INVALID_PW    = 114

	ERROR_CODE_ROOM_ENTER_PACKET_DECODING         = 141
	ERROR_CODE_ROOM_ENTER_INVALID_STATE           = 142
	ERROR_CODE_ROOM_ENTER_INVALID_ROOM_NUM        = 143
	ERROR_CODE_ENTER_ROOM_MQ_PACKET_DECODING_FAIL = 144

	ERROR_CODE_LEAVE_ROOM_MQ_PACKET_DECODING_FAIL = 151
	ERROR_CODE_LEAVE_ROOM_INVALID_STATE           = 152

)
